### ISSUE TITLE
Switch from Travis-CI to GitHub Actions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-rewrites#125]
we're looking to reduce Travis-CI usage in scala/*

(as per https://github.com/scala/scala-dev/issues/785)

volunteer?

**Comment by ghostbuster91** [comment]
Seems like you have done it already. Is there anything left I could help with?

**Comment by SethTisue** [comment]
ah, so I did! it's only an oversight that I didn't close this ticket.

> Is there anything left I could help with?

w/r/t GitHub Actions specifically?

**Comment by ghostbuster91** [comment]
> w/r/t GitHub Actions specifically?

Yeah, I meant github actions, but since you said that it was only an oversights with the ticket being left open I guess that you are good :)
