### ISSUE TITLE
incorrect Any2StringAdd fix

### ISSUE THREAD

**Issue by ohze** [scala/scala-rewrites#18]
https://github.com/scala/scala-rewrites/blob/8b694270f736711cf51b54c07358522426dd460d/rewrites/src/main/scala/fix/scala213/Any2StringAdd.scala#L31

Should use `String.valueOf` instead of `.toString` to prevent NPE

**Comment by dwijnand** [comment]
You're right:

```scala
  implicit final class any2stringadd[A](private val self: A) extends AnyVal {
    def +(other: String): String = String.valueOf(self) + other
  }
```
