### ISSUE TITLE
Adding the collection rewrites

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-rewrites#3]
https://github.com/scala/scala-collection-compat also contains the Scalafix rewrites for the Scala 2.13 collections.

@julienrf, @szeiger mentioned that perhaps these two should merge.  I don't have any problem merging in any direction, but I propose that:

* I transfer this repo to the scala org, and
* I/we merge in a filter-branch of the collection rewrites

WDYT?

**Comment by julienrf** [comment]
That looks good!

**Comment by dwijnand** [comment]
@lrytz ping me when you're back and let's chat about this.

I started doing this (https://github.com/dwijnand/scala-rewrites/tree/merge-in-collection-rewrites), but the rewrites are written in terms of the scala.collection.compat library, so maybe it makes more sense to merge this repo into scala-collection-compat (and rename it).

Also, btw, those rewrites are available as `"org.scala-lang.modules" %% "scala-collection-migrations" % "2.0.0"`!

**Comment by dwijnand** [comment]
I feel like we missed the boat on this.
