### ISSUE TITLE
Make ExplicitNonNullaryApply work with scala 2.13

### ISSUE THREAD

**Issue by ohze** [scala/scala-rewrites#31]
Similar to scalacenter/scalafix#998

When migrating projects to scala 3, ExplicitNonNullaryApply must be applied to scala 2.13 source files (in `src/{main | test}/{scala | scala-2.13 | scala-2.13+ | ...}` directories)

**Comment by olafurpg** [comment]
I don't think you will need to change anything except compile/publish for 2.13 when Scalafix v1 is released. Currently, Scalafix rules can only compile against 2.12 but for Scalafix v1 it will run on 2.13 instead.
