### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by giabao** [scala/scala-rewrites#32]
We should publish `scala-rewrites` to maven central and update usage guide.

**Comment by anilkumarmyla** [comment]
+1, came here to use rule ExplicitNonNullaryApply, but could not find these rules on maven central https://scalacenter.github.io/scalafix/docs/users/installation.html#run-custom-rules

**Comment by SethTisue** [comment]
@dwijnand you might want to update https://github.com/scala/scala/pull/8833 to reflect current reality

**Comment by dwijnand** [comment]
Published:

* https://github.com/scala/scala-rewrites/releases/tag/v0.1.0
* https://travis-ci.com/github/scala/scala-rewrites/jobs/356391418
* https://repo1.maven.org/maven2/org/scala-lang/scala-rewrites_2.12/0.1.0/
* https://repo1.maven.org/maven2/org/scala-lang/scala-rewrites_2.13/0.1.0/

Feedback/improvements, always welcome.

**Comment by SethTisue** [comment]
should https://github.com/scala/scala/releases/tag/v2.13.3 refer to it?

**Comment by dwijnand** [comment]
Now it can, absolutely!

**Comment by SethTisue** [comment]
feel free, then :-)

we could also tweet from scala_lang about it, if you're comfortable with that
